apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname  # 这里的 key 是节点的主机名标签
                    operator: In
                    values:
                      - k8s-master  # 指定你希望调度到的节点名称
      containers:
        - name: demo
          image: demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
