apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-deployment
  template:
    metadata:
      name: springboot-pod
      labels:
        app: springboot-deployment
    spec:
      containers:
        - name: demo
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      