apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080  # 服务的端口，即用户或其他服务访问该服务的端口
      targetPort: 8080  # 后端 Pod 的端口，即服务将请求转发到 Pod 的该端口
      nodePort: 30081 # 节点端口，允许从集群外通过 <NodeIP>:<nodePort> 访问该服务